### ISSUE TITLE
Checkpoint 1 is ready for review

### ISSUE THREAD

**Issue by amoose20** [amoose20/indieProject#1]
@pawaitemadisoncollege 

Checkpoint 1 is ready for review!

**Comment by pawaitemadisoncollege** [comment]
Hi @amoose20. This is a solid start on your indie project! 

**Problem Statement**

Effectively explains the background, problem to be solved and solution. 
- [ ] Small typo: collegeiate
- [ ] Consider adding a list of technologies so that a prospective employer looking at this as part of your portfolio can easily see what tech you are using.

**Journal and Time Log**

Up-to-date and includes details to communicate time spent, what was done and a reflection on how things are going/areas for improvement. 

**User Stories**

Appear to cover most requirements and objectives of the class project.
- [ ] I don't think delete is covered in the user stories. Is there a meaningful user story that you could include that would involve deleting?

**Screens**

- [ ] We will be using AWS Cognito for authentication. It can provide sign up and sign in screens, so you may not need to worry about building those particular JSPs (it's good to have them represented in the screen design though!)
- [ ] Are all user stories represented in the screen design? Saving preferred sports books, for example?

**Project Plan**

- [ ] Depending how you work best, consider listing specific user stories in the plan and include when you will start each story and when you are targeting finishing it.
- [ ] It may helpful to break down the individual stories into tasks and list those in the plan or put them into a tool like Trello. Again, this depends on how you like to plan and work.
- [ ] If you already have a proven planning system that works well for you, please use it and ignore the items above.
